#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Tuan Nguyen Anh Resume
url: "https://anhtuank7c.github.io"

#change it according to your repository name
# disabling since we are using a custom domain
#baseurl: '/online-cv'
description: |
  I've worked with React Native framework since 2016 up to now, and I do both backend and frontend websites that uses ReactJS/SvelteKit, PostgreSQL, Elysia, NodeJS, Redis.
  I don't hesitate to dig into a problem, analyze it, and resolve it with a clear refinement. No one is perfect, but I listen to others in order to improve.
  I am full of positive energy to learn new things and improve my skills day by day.
  I have done remote work since 2018, and have no problem with distractions by using the Pomodoro Technique to manage the focus.

# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: turquoise # blue turquoise green berry orange ceramic
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

# Tracker
analytics: UA-128129447-1

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
