#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Tuan Nguyen Anh Resume
url: 'https://cv.anhtuank7c.dev'

#change it according to your repository name
# disabling since we are using a custom domain
#baseurl: '/online-cv' 

description: Results-driven Senior Software Engineer with 8+ years of experience architecting scalable solutions across mobile, web, and enterprise platforms. Proven track record of technical leadership, from optimizing infrastructure costs by 40% as CTO to delivering mission-critical features that increased user engagement by 30%. Passionate about clean architecture, code quality, and mentoring teams to achieve excellence in software delivery.
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: blue # blue turquoise green berry orange ceramic teal oceanstale
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

# Tracker
analytics: G-2MJXZZ175P

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
